### PR TITLE
Add # to legalTitleCharset

### PR DESCRIPTION
**Pull request by Daimona**
Rationale in the commit itself.

### CODE REVIEW

**Comment by valerio-bozzolan** [comment]
I don't know if it's a good idea per https://www.mediawiki.org/wiki/Manual:$wgLegalTitleChars.

Maybe we need some refactoring for anchors.

**Comment by Daimona** [comment]
It should, as long as the list is only used to build regexps. Maybe we could add a new legalWikilinkCharset() returning `'#' . legalTitleCharset()`?

**Comment by valerio-bozzolan** [comment]
I'm working on :) Just a sec.

**Comment by valerio-bozzolan** [comment]
I've a patch that allow this:

```php
<?php
require 'autoload.php';

use wm\WikipediaIt;
use mw\Wikilink;
use mw\CompleteTitle;

$wiki = WikipediaIT::instance();
$title = $wiki->createTitle( 'Asd' );
$wlink = $title->createWikilink();

echo $wlink->getRegex( [
    'title-group-name'  => 'title',
    'alias-group-name'  => 'alias',
    'anchor-group-name' => 'anchor', // added now!
] );
```

And generates this:

    \[\[[ _]*(?P<title>:?[ _]*[Aa]sd)( *#(?P<anchor>[ %!\"$&'()*,\-.\/0-9:;=?@A-Z\\^_`a-z~\x80-\xFF+]*))?([ _]*\|(?P<alias>.*?))?[ _]*\]\]

**Pull request merged**
